import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";

const Home = () => {
  return (
    <div className={"page-container"}>
      <Head>
        <title>Dan Abramov profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <aside>
        <div className="aside-container">
          <img
            src="/assets/images/Dan.jpeg"
            alt="Dan Abramov"
            className="aside-image"
          />
          <p className="aside-content">
            <p className="aside-title">
              Personal blog by
              <a
                href="https://mobile.twitter.com/dan_abramov"
                style={{ color: "rgb(209,47,104)" }}
              >
                Dan Abramov
              </a>
            </p>

            <p className="aside-subtitle">I explain with words and code.</p>
          </p>
        </div>
      </aside>
      <main>main</main>

      <style jsx>{`
        .page-container {
        }
        .aside-container {
          display: flex;
          margin-bottom: 3.5rem;
        }
        .aside-subtitle {
          margin: 0px;
        }
        .aside-title {
          margin-top: 0px;
          margin-bottom: 5px;
        }
        .aside-content {
          max-width: 310px;
          margin: 0px;
          font-size: 1.3rem;
        }
        .aside-image {
          margin-right: 0.875rem;
          width: 4.5rem;
          height: 4.5rem;
          border-radius: 50%;
        }
      `}</style>
    </div>
  );
};
Home.getLayout = function getLayout(page: any) {
  return (
    <Layout>
      <div>{page}</div>
    </Layout>
  );
};
export default Home;
