import Head from "next/head";
import { apiInstance } from "../apiInstance";
import Layout from "../components/Layout";
import PostItem from "../components/PostItem";
import { IPostItem } from "../components/PostItem";
interface IProps {
  posts: IPostItem[];
}

function PostList({ posts }: IProps) {
  return (
    <Layout>
      <div className={"page-container"}>
        <Head>
          <title>Dan Abramov profile</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <aside className="aside-container">
          <img
            src="/assets/images/Dan.jpeg"
            alt="Dan Abramov"
            className="aside-image"
          />
          <div className="aside-content">
            <p className="aside-title">
              Personal blog by
              <a
                href="https://mobile.twitter.com/dan_abramov"
                className="profile-link"
              >
                Dan Abramov
              </a>
            </p>

            <p className="aside-subtitle">I explain with words and code.</p>
          </div>
        </aside>
        <main>
          {posts.map((post: IPostItem) => {
            return <PostItem post={post} />;
          })}
        </main>
        <style jsx>{`
          .page-container {
          }
          .aside-container {
            display: flex;
            margin-bottom: 3.5rem;
          }
          .aside-subtitle {
            margin: 0px;
          }
          .aside-title {
            margin-top: 0px;
            margin-bottom: 20px;
          }
          .aside-content {
            max-width: 310px;
            margin: 0px;
            font-size: 1.3rem;
          }
          .aside-image {
            margin-right: 0.875rem;
            width: 4.5rem;
            height: 4.5rem;
            border-radius: 50%;
          }
          .profile-link {
            color: rgb(209, 47, 104);
            padding-left: 3px;
            text-decoration: underline;
          }
        `}</style>
      </div>
    </Layout>
  );
}

export default PostList;

export async function getStaticProps() {
  const res: any = await apiInstance("GET", "/posts", {});
  const data: any = res?.data?.posts ?? [];

  const sortedPosts = data.sort(function (a: any, b: any) {
    return a.id > b.id ? -1 : 1;
  });

  return {
    props: {
      posts: sortedPosts,
    },
  };
}
